### ISSUE TITLE
Some templatetag ain't removed by postprocess

### ISSUE THREAD

**Issue by ghost** [bennettaur/HTML-Template-Beautifier#1]
Hello, 
and first of all **thanks for this package**. It's really a good idea to apply the power of js-beautify to django templates. However, even if the template is really cleaned up and readable, I need to finish work by hand, some `templatetag` ain't removed by th postprocess.
For example see these two files: [base.html](https://dl.dropboxusercontent.com/u/94909585/base.html) and [beautified-base.html](https://dl.dropboxusercontent.com/u/94909585/beautified-base.html)
- Multiple lines comments `{# #}`  are collapsed to one line.
- The line `{% load compress %}` ain't post-processed
- `{% include " path/to/the/file "}` add space at the beginning and the end of the path.
- long lines as html `<link>` and `<body>` are split and incorrectly treated.

I tried to modify the regex but couldn't get it works.

**Comment by aquilante** [comment]
Hallo
I have forked the code on bitbucket https://bitbucket.org/aquilante/html-template-beautifier/overview
and I think I have fixed those issues.

I'm sorry but I'm not a node/js expert programmer so maybe I have added more bug then removed.
Please give it a try if you can and let me know your findings.

**Comment by ghost** [comment]
Bonjour,
I've started using @aquilante fork today and it seems to work nicely.
Thanks for sharing.
